
server:
  port: 8181
spring:
  application:
    name: serverconfig
  cloud:
    config:
      server:
        git:
         uri: https://github.com/Chaudement/serverconfigure
         username: chaudement
         password: wuyunjiaohua123*
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone:  http://${eureka.instance.hostname}:8761/eureka/

